language: node_js
node_js:
  - "6"
branches:
  only:
  - master
notifications:
  email: false
sudo: false                 
install:
  - npm install
before_script:
# 无其他依赖项所以执行npm run build 构建就行了
script:
  - npm run build
# script: npm run test